# -*- coding: utf-8 -*-
"""password_checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dk7XKVAfJ0PPIKTt8nbU2bBp8l4wWvTE
"""

import random
import string
import re
import math

def generate_password(length):
    characters = string.ascii_letters + string.digits + string.punctuation
    return ''.join(random.choice(characters) for _ in range(length))


def calculate_entropy(password):
    pool = 0
    if re.search(r"[a-z]", password):
        pool += 26
    if re.search(r"[A-Z]", password):
        pool += 26
    if re.search(r"[0-9]", password):
        pool += 10
    if re.search(r"[!@#$%^&*(),.?\":{}|<>]", password):
        pool += 32

    return len(password) * math.log2(pool) if pool > 0 else 0


def check_strength(password):
    score = 0
    if len(password) >= 8:
        score += 1
    if re.search(r"[a-z]", password):
        score += 1
    if re.search(r"[A-Z]", password):
        score += 1
    if re.search(r"[0-9]", password):
        score += 1
    if re.search(r"[!@#$%^&*(),.?\":{}|<>]", password):
        score += 1

    entropy = calculate_entropy(password)

    if score <= 2 or entropy < 40:
        return "WEAK", entropy
    elif score <= 4 or entropy < 60:
        return "MEDIUM", entropy
    else:
        return "STRONG", entropy


# ---------------- MAIN PROGRAM ----------------
print("🔐 Password Generator & Strength Checker")

choice = input("Do you want to continue? (yes/no): ").strip().lower()

if choice == "no":
    print("Thank you")

elif choice == "yes":
    print("\n1. Generate a password")
    print("2. Check your own password")

    option = input("Choose option (1/2): ").strip()

    if option == "1":
        length_input = input("Enter password length (minimum 8): ")

        if not length_input.isdigit():
            print("Invalid input. Please enter a NUMBER only.")
        else:
            length = int(length_input)
            if length < 8:
                print("Password length must be at least 8.")
            else:
                password = generate_password(length)
                strength, entropy = check_strength(password)
                print("\nGenerated Password:", password)
                print("Strength:", strength)
                print("Entropy:", round(entropy, 2))

    elif option == "2":
        password = input("Enter your password: ")
        strength, entropy = check_strength(password)
        print("\nPassword:", password)
        print("Strength:", strength)
        print("Entropy:", round(entropy, 2))

    else:
        print("Invalid option. Please choose 1 or 2.")

else:
    print("Invalid choice. Please enter yes or no.")